### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by ghzxs** [usamaeltmsah/Safari-Darkula#1]
How to install it on iPhone

**Comment by usamaeltmsah** [comment]
Thank you @ghzxs for showing interest in my project.
## To install this app:-
1. you have to have Xcode, as it's an iOS app.
2. When the app is built you will get the app on your device.
3. You have to select the theme you're interested in, and do you like it to be on or off or auto (auto means it will be based on whether you're in the morning or at night).
4. So you can select `ON` if you need it to be always enabled.
5. You can find the descriptions for each within the app.
6. Then you visit Safari and behind the URL field you can find **`AA`** select it and enable the extension from Manage extensions.
7. Then you select the dark mode extension and from the popup, you can choose the mode you like. 
8. Enable it for the websites you need or all the websites.

Please let me know if it helps, so I can close the issue

### Enjoy using the app!!
